In [1]:
ldata1 = ['red','green','blue']
result1 = ' '.join(ldata1)
result1

'red green blue'

In [2]:
result2 = '-'.join(ldata1)

In [3]:
result2

'red-green-blue'

In [4]:
result3 = '.'join(ldata1)
result3

SyntaxError: invalid syntax (<ipython-input-4-cdc780bcb7ce>, line 1)

In [5]:
result3 = []
for i in range(10):
    result3.append(i)
result3

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
result4 = [i for i in range(10)]

In [7]:
result4

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
type(result4)


list

In [10]:
result5 = []
for i in range(10):
    if i %2 == 0:
        result5.append(i)
result5

[0, 2, 4, 6, 8]

In [11]:
result6 = [i for i in range(10) if i % 2 == 0]
result6

[0, 2, 4, 6, 8]

In [12]:
result7 = []
for i in range(10):
    if i %2 == 0:
        result7.append(i)
    else:
        result7.append(10)
result7

[0, 10, 2, 10, 4, 10, 6, 10, 8, 10]

In [13]:
result8 = [i if i%2 == 0 else 10 for i in range(10)]
result8

[0, 10, 2, 10, 4, 10, 6, 10, 8, 10]

In [14]:
result8 = [i if i%2 == 0 for i in range(10)]
result8

SyntaxError: invalid syntax (<ipython-input-14-5734b1c880d3>, line 1)

In [16]:
word1 = 'Hello'
word2 = 'World'

result9 = [i +j for i in word1 for j in word2]
print(result9)

['HW', 'Ho', 'Hr', 'Hl', 'Hd', 'eW', 'eo', 'er', 'el', 'ed', 'lW', 'lo', 'lr', 'll', 'ld', 'lW', 'lo', 'lr', 'll', 'ld', 'oW', 'oo', 'or', 'ol', 'od']


In [17]:
word1 = 'Hello'
word2 = 'World'

result10 = [i +j for i in word1 for j in word2 if not i == j]
print(result10)

['HW', 'Ho', 'Hr', 'Hl', 'Hd', 'eW', 'eo', 'er', 'el', 'ed', 'lW', 'lo', 'lr', 'ld', 'lW', 'lo', 'lr', 'ld', 'oW', 'or', 'ol', 'od']


In [18]:
type(result10)

list

In [19]:
strs = 'the quick brown fox jumps over the lazy dog'
result11 = [ [w.upper(),w.lower(),len(w)] for w in strs.split()]
result11

[['THE', 'the', 3],
 ['QUICK', 'quick', 5],
 ['BROWN', 'brown', 5],
 ['FOX', 'fox', 3],
 ['JUMPS', 'jumps', 5],
 ['OVER', 'over', 4],
 ['THE', 'the', 3],
 ['LAZY', 'lazy', 4],
 ['DOG', 'dog', 3]]

In [20]:
ldata1 = ['orange','yellow','red']
for i, v in enumerate(ldata1):
    print(i,v,sep=':')

0:orange
1:yellow
2:red


In [21]:
result1 = {i:j for i , j in enumerate('teamlab is an academic institude located in South Korea'.split())}
result1

{0: 'teamlab',
 1: 'is',
 2: 'an',
 3: 'academic',
 4: 'institude',
 5: 'located',
 6: 'in',
 7: 'South',
 8: 'Korea'}

In [22]:
ldata1 = [30,20,10,50]
ldata2 = ['kim','lee','choi','oh']
ldata3 = [175,185,165,155]

for i in zip(ldata1, ldata2, ldata3):
    print(i)

(30, 'kim', 175)
(20, 'lee', 185)
(10, 'choi', 165)
(50, 'oh', 155)


In [24]:
ldata1 = [30,20,10,50]
ldata2 = ['kim','lee','choi','oh']
ldata3 = [175,185,165,155]

for a,n,h in zip(ldata1, ldata2, ldata3):
    print(f'age:{a}, name:{n}, height:{h}')

age:30, name:kim, height:175
age:20, name:lee, height:185
age:10, name:choi, height:165
age:50, name:oh, height:155


In [25]:
t1 = (4,5,8)
t2 = (55, 77 , 11)
t3 = (333, 444, 888)

for a,b,c in zip(t1,t2,t3):
    print( a+b+c ,'\n')

392 

526 

907 



In [26]:
t1 = (4,5,8)
t2 = (55, 77 , 11)
t3 = (333, 444, 888)

result1 = [x+y+z for x, y,z in zip(t1,t2,t3)]
result1

[392, 526, 907]

In [27]:
result1 = [sum(x) for x in zip(t1,t2,t3)]
result1

[392, 526, 907]

In [28]:
def f1(x,y) : 
    return x + 10 + y
f1(10,20)

40

In [29]:
f2 = lambda x,y : x + 10 + y
f2(10,20)

40

In [30]:
ex = [1,2,3,4,5]

In [32]:
type(ex)

list

In [34]:
ex = {1,2,3,4,5}

In [35]:
type(ex)

set

In [36]:
ldata2 = [1,2,3,4,5]
def f3(x):
    return x**2
list(map(f3,ldata2))

[1, 4, 9, 16, 25]

In [37]:
list(map(lambda x:x**2, ldata2))

[1, 4, 9, 16, 25]

In [39]:
ldata3 = [5,2,9,8,1,4]
ldata3.sort(reverse = True)
ldata3

[9, 8, 5, 4, 2, 1]

In [40]:
ldata4 = [[10,'lee'],[60,'oh'], [30,'kim'],[40,'choi']]
ldata4

[[10, 'lee'], [60, 'oh'], [30, 'kim'], [40, 'choi']]

In [41]:
type(ldata4)

list

In [43]:
ldata4.sort(key=lambda x :x[1])
ldata4

[[40, 'choi'], [30, 'kim'], [10, 'lee'], [60, 'oh']]

In [44]:
ldata4.sort(key=lambda x :x[1][::-1])
ldata4

[[10, 'lee'], [60, 'oh'], [40, 'choi'], [30, 'kim']]

In [45]:
ldata4.sort(key=lambda x :x[1], reverse=True)
ldata4

[[60, 'oh'], [10, 'lee'], [30, 'kim'], [40, 'choi']]

In [56]:
class Person:
    
    def __init__(self):
        self.name = 'kim'
        self.age = 30
    
    def print_info(self):
        print('name:{} age:{}'.format(self.name,self.age))
    
    def walk(self):
        print('walking')
    def speak(self):
        print('speaking')

In [57]:
p1 = Person()
p1.walk()
p1.speak()

walking
speaking


In [59]:
p2 = Person()
p2.print_info()

name:kim age:30


In [64]:
class Person3:
    
    def __init__(self,name,age = 0):
        self.name = name
        self.age = age
    
    def print_info(self):
        print('name:{} age:{}'.format(self.name,self.age))
    
    def walk(self):
        print('walking')
    def speak(self):
        print('speaking')

In [65]:
p3 = Person3('lee')
p3.print_info()

name:lee age:0


In [69]:
class Phone : 
    def call(self, number):
        print(number, '에게 전화를 겁니다.')
    def sendMessage(self, number):
        print(number, '에게 메세지를 보냅니다')

In [70]:
class D_Phone(Phone):
    def take_picture(self):
        print('사진을 찍습니다.')

In [72]:
obj1 = D_Phone()
obj1.take_picture()

사진을 찍습니다.


In [73]:
obj1.call('010-2222-2422')

010-2222-2422 에게 전화를 겁니다.


In [74]:
obj1.sendMessage('010-4314-1241')

010-4314-1241 에게 메세지를 보냅니다


In [97]:
class Phone2 : 
    def __init__(self):
        print('__Phone2_init')
        self.maker = 'LG'
    
    def call(self, number):
        print(number, '에게 전화를 겁니다.')
    def sendMessage(self, number):
        print(number, '에게 메세지를 보냅니다')

In [98]:
class D_Phone2(Phone2):
    def __init__(self):
        super().__init__()
        print('__Dphone_init')
    
    def take_picture(self):
        print('사진을 찍습니다.')
    def phone_info(self):
        print(f'maker:{self.maker}')

In [99]:
obj2 = D_Phone2()
obj2.phone_info()

__Phone2_init
__Dphone_init
maker:LG


In [100]:
iter1 = range(3).__iter__()

In [101]:
iter1

In [103]:
iter1.__next__()

0

In [104]:
iter1.__next__()

1

In [105]:
iter1.__next__()

2

In [106]:
iter1.__next__()

StopIteration: 

In [107]:
ddata = {'name':'choi','age':20, 'height':182}
ddata.keys()

dict_keys(['name', 'age', 'height'])

In [108]:
##dict supports iterator
##This can be used in for loop

In [109]:
for k in ddata.keys():
    print(k)

name
age
height


In [110]:
for i in [ 6,3,2,5,3]:
    print(i)

6
3
2
5
3


In [111]:
## class도 __iter__() 와 __next__() 구현을 하면 for loop 사용할 수 있음

In [ ]:
class CustomRange:
    def __init__(self,start,end):
        self.current = start
        self.end = end
    def __iter__(self):
        return self
    def __next__(self):
        if self.current <self.end:
            rvalue = self.current
            self.current +=1
            return rvalue
        else:
            raise StopIteration

In [ ]:
for i in CustomRange(1,5):
    print(i)

# file = open('test.txt','w')
file1.write('hi everyone')
file1.close()

In [6]:
file1 = open('test.txt','w')
file1.write('hi everyone')
file1.close()

In [7]:
file2 = open('test.txt','r')
rstr = file2.read()
print('읽어온 문자열 : ' , rstr)
file2.close()

읽어온 문자열 :  hi everyone


In [9]:
infile1 = open('FirstPresidents.txt','r')
for line in infile1:
    print(line.rstrip())
infile1.close()

George Washington
John Adams
Thomas Jefferson


In [10]:
infile2 = open('FirstPresidents.txt','r')
ldata1 = [line for line in infile2]
ldata1

['George Washington\n', 'John Adams\n', 'Thomas Jefferson\n']

In [11]:
infile2 = open('FirstPresidents.txt','r')
ldata1 = [line.rstrip() for line in infile2]
ldata1

['George Washington', 'John Adams', 'Thomas Jefferson']

In [34]:
infile3 = open('States.txt','r')
ldata2 = [line for line in infile3]
ldata2.sort(key=lambda x :x[1])

In [35]:
ldata2

['Massachusetts\n',
 'Maryland\n',
 'Maine\n',
 'California\n',
 'Kansas\n',
 'Washington\n',
 'Hawaii\n',
 'Idaho\n',
 'Delaware\n',
 'Pennsylvania\n',
 'New Jersey\n',
 'Georgia\n',
 'New Hampshire\n',
 'New York\n',
 'Vermont\n',
 'Kentucky\n',
 'Tennessee\n',
 'Texas\n',
 'West Virginia\n',
 'Nevada\n',
 'Nebraska\n',
 'New Mexico\n',
 'Rhode Island\n',
 'Ohio\n',
 'Virginia\n',
 'Mississippi\n',
 'Missouri\n',
 'Michigan\n',
 'Wisconsin\n',
 'Minnesota\n',
 'Oklahoma\n',
 'Illinois\n',
 'Alabama\n',
 'Florida\n',
 'Alaska\n',
 'Indiana\n',
 'Connecticut\n',
 'South Carolina\n',
 'North Carolina\n',
 'Louisiana\n',
 'Iowa\n',
 'Colorado\n',
 'North Dakota\n',
 'South Dakota\n',
 'Montana\n',
 'Arkansas\n',
 'Oregon\n',
 'Arizona\n',
 'Utah\n',
 'Wyoming\n']

In [36]:
outfile1 = open('StateAlpha.txt','w')
outfile1.writelines(ldata2)
outfile1.close()

In [47]:
infile1 = open('USPres.txt','r')
infile2 = open('VPres.txt','r')

ldata1 = [line for line in infile1]

outfile1 = open('Both.txt','w')

for vp in infile2:
    if vp in ldata1:
        outfile1.write(vp)
        
infile1.close()
infile2.close()
outfile1.close()

In [145]:
infile1 = open('USPres.txt','r')
infile2 = open('VPres.txt','r')

sdata1 = set([line for line in infile1])
sdata2 = {line for line in infile2}

sMix = sdata1.intersection(sdata2)

sdata = sorted(sMix)
cdata = list(sMix)

print(sdata)
print('\n')
print(cdata)
outfile2 = open('Both3.txt','w')
outfile2.writelines(cdata)

infile1.close()
infile2.close()
outfile2.close()

['Andrew Johnson\n', 'Calvin Coolidge\n', 'Chester Arthur\n', 'George H. W. Bush\n', 'Gerald Ford\n', 'Harry Truman\n', 'John Adams\n', 'John Tyler\n', 'Lyndon Johnson\n', 'Martin Van Buren\n', 'Millard Fillmore\n', 'Richard Nixon\n', 'Theodore Roosevelt\n', 'Thomas Jefferson\n']


['Thomas Jefferson\n', 'John Adams\n', 'Chester Arthur\n', 'Harry Truman\n', 'Theodore Roosevelt\n', 'Lyndon Johnson\n', 'George H. W. Bush\n', 'Andrew Johnson\n', 'Calvin Coolidge\n', 'Richard Nixon\n', 'John Tyler\n', 'Millard Fillmore\n', 'Gerald Ford\n', 'Martin Van Buren\n']


In [51]:
with open('test.txt','r') as file:
    rdata = file.read()
    print(rdata)

hi everyone


In [52]:
import os

os.mkdir('log')

In [57]:
import os

if not os.path.isdir('log'):
    os.mkdir('log')
    
if not os.path.exists('log/count_log.txt'):
    f = open('log/count_log.txt','w', encoding = 'utf8')
    f.write('기록 시작 \n\n')
    f.close()
    
    
with open('log/count_log.txt','a', encoding = 'utf8') as f:
    import random, datetime
    for i in range(5):
        stamp = str(datetime.datetime.now())
        value  = random.random() * 1000000
        log_line = stamp + '\t' + str(value) + ' 값이 생성되었습니다.\n'
        f.write(log_line)
        

In [64]:
import numpy as np
ldata1 = [4,7,5.5,8,10]
ldata1

[4, 7, 5.5, 8, 10]

In [60]:
arr1 = np.array(ldata1)
arr1

array([ 4. ,  7. ,  5.5,  8. , 10. ])

In [62]:
type(arr1)

numpy.ndarray

In [63]:
type(ldata1)

list

In [65]:
arr2 = np.array(ldata1,dtype=np.int32)
arr2

array([ 4,  7,  5,  8, 10], dtype=int32)

In [66]:
ldata2 = [[6,3,8],[7,2,5]]

In [67]:
ldata2

[[6, 3, 8], [7, 2, 5]]

In [68]:
arr3 = np.array(ldata2)
arr3

array([[6, 3, 8],
       [7, 2, 5]])

In [69]:
arr3.shape, arr3.dtype

((2, 3), dtype('int64'))

In [70]:
arr4 = arr3.astype(np.float32)
arr4

array([[6., 3., 8.],
       [7., 2., 5.]], dtype=float32)

In [71]:
arr1 = np.arange(1,10,2)
arr1

array([1, 3, 5, 7, 9])

In [74]:
arr1 = np.arange(1,100,2)


In [75]:
arr2 = np.linspace(-3,3,10)

In [76]:
arr2

array([-3.        , -2.33333333, -1.66666667, -1.        , -0.33333333,
        0.33333333,  1.        ,  1.66666667,  2.33333333,  3.        ])

In [80]:
arr3 = np.ones([3,4])
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
arr4 = np.zeros([3,4])
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [81]:
arr5 = np.empty([3,4])
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [82]:
arr3 = np.ones([3,4])
arr3

arr5 = np.empty([3,4])
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
##empty는 현제 메모리의 잔여 값을 띄워줌

In [84]:
arr1 = np.array([[4,2,1],[8,3,5]])
arr2 = np.array([[5,1,3],[9,2,4]])
arr1


array([[4, 2, 1],
       [8, 3, 5]])

In [85]:
arr2

array([[5, 1, 3],
       [9, 2, 4]])

In [86]:
arr1 + arr2

array([[ 9,  3,  4],
       [17,  5,  9]])

In [88]:
arr1 *3

array([[12,  6,  3],
       [24,  9, 15]])

In [89]:
1/arr1

array([[0.25      , 0.5       , 1.        ],
       [0.125     , 0.33333333, 0.2       ]])

In [90]:
arr1 > arr2

array([[False,  True, False],
       [False,  True,  True]])

In [92]:
arr1 = np.array([5,3,2,6,3,7,8,9])
arr1

array([5, 3, 2, 6, 3, 7, 8, 9])

# 

In [93]:
arr1[1], arr1[-1]

(3, 9)

In [94]:
arr1[1:5]

array([3, 2, 6, 3])

In [95]:
arr1[4] = 2000
arr1

array([   5,    3,    2,    6, 2000,    7,    8,    9])

In [97]:
arr2 = np.array([[4,2,8,9],[1,7,5,3],[6,9,2,1]])
arr2

array([[4, 2, 8, 9],
       [1, 7, 5, 3],
       [6, 9, 2, 1]])

In [99]:
arr2[1][1] , arr2[1,1]

(7, 7)

In [100]:
arr2[1:, 2:]

array([[5, 3],
       [2, 1]])

In [101]:
arr2[1:][2:]

array([], shape=(0, 4), dtype=int64)

In [104]:
arr3 = np.array([[3,6,1],
                [9,7,2]])
arr3

array([[3, 6, 1],
       [9, 7, 2]])

In [105]:
barr1 = np.array([[False,True,False],[True,False,True]])
barr1

array([[False,  True, False],
       [ True, False,  True]])

In [106]:
arr3[barr1]

array([6, 9, 2])

In [115]:
barr2 = np.array([False,True])
arr3[barr2]

array([[9, 7, 2]])

In [132]:
barr3 = np.array([True,True,False])
arr3[1:2,2]

array([2])

In [133]:
arr3[0:2,2]

array([1, 2])

In [134]:
arr3[0:,2]

array([1, 2])

In [135]:
np.random.seed(12345)

In [136]:
data = np.random.randn(7,4)
data

array([[-0.20470766,  0.47894334, -0.51943872, -0.5557303 ],
       [ 1.96578057,  1.39340583,  0.09290788,  0.28174615],
       [ 0.76902257,  1.24643474,  1.00718936, -1.29622111],
       [ 0.27499163,  0.22891288,  1.35291684,  0.88642934],
       [-2.00163731, -0.37184254,  1.66902531, -0.43856974],
       [-0.53974145,  0.47698501,  3.24894392, -1.02122752],
       [-0.5770873 ,  0.12412128,  0.30261356,  0.52377207]])

In [137]:
names = np.array(['bob','joe','will','bob','will','joe','joe'])
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [140]:
data[names == 'bob']

array([[-0.20470766,  0.47894334, -0.51943872, -0.5557303 ],
       [ 0.27499163,  0.22891288,  1.35291684,  0.88642934]])

In [142]:
data[names == 'bob',2:]

array([[-0.51943872, -0.5557303 ],
       [ 1.35291684,  0.88642934]])

In [143]:
data[data>0]

array([0.47894334, 1.96578057, 1.39340583, 0.09290788, 0.28174615,
       0.76902257, 1.24643474, 1.00718936, 0.27499163, 0.22891288,
       1.35291684, 0.88642934, 1.66902531, 0.47698501, 3.24894392,
       0.12412128, 0.30261356, 0.52377207])

In [144]:
np.where(data>0,data, 0)

array([[0.        , 0.47894334, 0.        , 0.        ],
       [1.96578057, 1.39340583, 0.09290788, 0.28174615],
       [0.76902257, 1.24643474, 1.00718936, 0.        ],
       [0.27499163, 0.22891288, 1.35291684, 0.88642934],
       [0.        , 0.        , 1.66902531, 0.        ],
       [0.        , 0.47698501, 3.24894392, 0.        ],
       [0.        , 0.12412128, 0.30261356, 0.52377207]])