In [1]:
import numpy as np

In [2]:
arr1 = np.arange(10)

In [3]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.square(arr1)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [7]:
np.exp(arr1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [8]:
np.sin(arr1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [9]:
np.cos(arr1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [10]:
arr2 = np.array([4,2,1,7,8])
arr3 = np.array([5,1,4,6,9])

In [11]:
np.maximum(arr2, arr3)

array([5, 2, 4, 7, 9])

In [12]:
arr4 = np.array([32.522,74.437,814.888,123.657])

In [14]:
np.modf(arr4)

(array([0.522, 0.437, 0.888, 0.657]), array([ 32.,  74., 814., 123.]))

In [15]:
arr5 = np.arange(8)
arr5

array([0, 1, 2, 3, 4, 5, 6, 7])

In [17]:
arr6 = arr5.reshape(4,2)
arr6

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [18]:
arr6.T

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [22]:
xarr = np.array([1.1,1.2,1.3,1.4])
yarr = np.array([2.1,2.2,2.3,2.4])
cond = np.array([False,True,False,True])

In [23]:
result = [x if c else y for x,y,c in zip(xarr,yarr,cond)]
result

[2.1, 1.2, 2.3, 1.4]

In [26]:
result2 = np.where(cond, xarr,yarr)
result2

array([2.1, 1.2, 2.3, 1.4])

In [27]:
np.random.seed(12356)

arr7  = np.random.randn(4,4)

arr7

array([[ 0.68725069, -0.16282407, -2.05953155,  1.53661965],
       [-1.00116073,  0.45209152,  0.93103451,  0.1067964 ],
       [-0.45309061,  0.71110858,  0.24184678,  0.4600953 ],
       [ 0.34713803,  0.95536287, -0.11774967,  0.84264266]])

In [29]:
result3 = np.where(arr7>0,arr7,0)
result3

array([[0.68725069, 0.        , 0.        , 1.53661965],
       [0.        , 0.45209152, 0.93103451, 0.1067964 ],
       [0.        , 0.71110858, 0.24184678, 0.4600953 ],
       [0.34713803, 0.95536287, 0.        , 0.84264266]])

In [34]:
arr8 = np.random.randn(4,5)
arr8

array([[-0.09708452,  0.1914938 ,  0.57547384,  0.32740239,  0.54563619],
       [ 0.94355721,  0.06103571,  0.66705938,  1.15621229, -1.35710137],
       [-0.29227527,  0.13620548,  1.13152781,  1.10625046,  0.79058984],
       [-1.09022479,  1.34155243,  2.37138758, -0.35374675, -1.19044333]])

In [42]:
arr8.mean(), arr8.mean(0) #열별 평균, arr8.mean(1)#행별 평균

(0.3482254195536821,
 array([-0.13400684,  0.43257186,  1.18636215,  0.5590296 , -0.30282967]))

In [43]:
arr8.std(1)

array([0.24740862, 0.90387122, 0.56269615, 1.40865048])

In [44]:
arr8.sum(0)

array([-0.53602737,  1.73028743,  4.74544861,  2.23611839, -1.21131867])

In [45]:
arr9 = np.arange(8)
arr9

array([0, 1, 2, 3, 4, 5, 6, 7])

In [47]:
arr9.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

In [48]:
arr10 = np.arange(9)

In [55]:
arr11 = arr10.reshape(3,3)

arr11

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
arr11.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [56]:
arr11.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36])

In [57]:
arr11.cumprod(0)

array([[ 0,  1,  2],
       [ 0,  4, 10],
       [ 0, 28, 80]])

In [58]:
arr11.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [59]:
arr11.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [60]:
arr1 = np.array([-1.23,5,-4,8,3])
arr1

array([-1.23,  5.  , -4.  ,  8.  ,  3.  ])

In [61]:
(arr1>0).sum()

3

In [62]:
bools = np.array([[False,True,True,False],
                 [False, False, True, False]])
bools

array([[False,  True,  True, False],
       [False, False,  True, False]])

In [63]:
bools.all(0)

array([False, False,  True, False])

In [64]:
bools.all(1)

array([False, False])

In [65]:
bools.any(0)

array([False,  True,  True, False])

In [70]:

arr3 = np.random.randn(10,4) *2
arr3

array([[-4.71883761, -0.39908591, -3.08399106, -1.94147182],
       [-2.6140605 ,  0.57269949,  0.75596822, -1.50777307],
       [ 0.6625713 ,  2.69948443,  0.13975338,  0.49334822],
       [-0.0237232 ,  2.00962318,  2.65438923, -1.83852312],
       [-3.09821288,  0.0443692 ,  1.51672629, -1.32104866],
       [ 1.72516017, -0.0200638 ,  0.10001871,  1.34043119],
       [ 1.70593006, -1.9117377 , -0.04698664, -4.60846776],
       [-1.30493768, -2.43660395, -2.66521942,  2.14924538],
       [ 1.44728301,  1.38000371,  2.00308688, -1.00617478],
       [-1.24454845, -1.84233722, -1.45242699,  0.44579109]])

In [73]:
arr3[(arr3>2).any(1)]

array([[ 0.6625713 ,  2.69948443,  0.13975338,  0.49334822],
       [-0.0237232 ,  2.00962318,  2.65438923, -1.83852312],
       [-1.30493768, -2.43660395, -2.66521942,  2.14924538],
       [ 1.44728301,  1.38000371,  2.00308688, -1.00617478]])

In [74]:
(arr3>2).any(1)

array([False, False,  True,  True, False, False, False,  True,  True,
       False])

In [75]:
(arr3>2)

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [False, False,  True, False],
       [False, False, False, False]])

In [76]:
arr3[(arr3>2)]

array([2.69948443, 2.00962318, 2.65438923, 2.14924538, 2.00308688])

In [79]:
arr3[(arr3>2).any(1),1:]

array([[ 2.69948443,  0.13975338,  0.49334822],
       [ 2.00962318,  2.65438923, -1.83852312],
       [-2.43660395, -2.66521942,  2.14924538],
       [ 1.38000371,  2.00308688, -1.00617478]])

In [80]:
arr3[(arr3>2).any(1)]

array([[ 0.6625713 ,  2.69948443,  0.13975338,  0.49334822],
       [-0.0237232 ,  2.00962318,  2.65438923, -1.83852312],
       [-1.30493768, -2.43660395, -2.66521942,  2.14924538],
       [ 1.44728301,  1.38000371,  2.00308688, -1.00617478]])

In [81]:
arr3[(arr3>2).any(1),1:]

array([[ 2.69948443,  0.13975338,  0.49334822],
       [ 2.00962318,  2.65438923, -1.83852312],
       [-2.43660395, -2.66521942,  2.14924538],
       [ 1.38000371,  2.00308688, -1.00617478]])

In [82]:
arr4 = np.random.randn(5,3)
arr4

array([[ 0.0513161 , -1.15771947,  0.81670694],
       [ 0.43360961,  1.01073695,  1.82487521],
       [-0.99751825,  0.8505911 , -0.1315776 ],
       [ 0.91241415,  0.18821068,  2.16946144],
       [-0.1149282 ,  2.00369736,  0.02961015]])

In [85]:
arr4.sort(0)
arr4

array([[-0.99751825, -1.15771947, -0.1315776 ],
       [-0.1149282 ,  0.18821068,  0.02961015],
       [ 0.0513161 ,  0.8505911 ,  0.81670694],
       [ 0.43360961,  1.01073695,  1.82487521],
       [ 0.91241415,  2.00369736,  2.16946144]])

In [86]:
arr4.sort(1)
arr4

array([[-1.15771947, -0.99751825, -0.1315776 ],
       [-0.1149282 ,  0.02961015,  0.18821068],
       [ 0.0513161 ,  0.81670694,  0.8505911 ],
       [ 0.43360961,  1.01073695,  1.82487521],
       [ 0.91241415,  2.00369736,  2.16946144]])

In [87]:
values = np.array([5,0,1,3,2])
indexer = values.argsort()
values

array([5, 0, 1, 3, 2])

In [88]:
indexer

array([1, 2, 4, 3, 0])

In [89]:
#argsory 중요 딱 index만 가져오는 sort

In [90]:
values[indexer]

array([0, 1, 2, 3, 5])

In [91]:
arr5 = np.random.randn(3,5)
arr5[0] = values
arr5

array([[ 5.        ,  0.        ,  1.        ,  3.        ,  2.        ],
       [-1.56565729, -0.56254019, -0.03266414, -0.9290062 , -0.48257265],
       [-0.03626385,  1.09539006,  0.98092848, -0.58948769,  1.58170009]])

In [92]:
arr5[:, arr5[0].argsort()]

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [-0.56254019, -0.03266414, -0.48257265, -0.9290062 , -1.56565729],
       [ 1.09539006,  0.98092848,  1.58170009, -0.58948769, -0.03626385]])

In [99]:
arr5 = np.random.randn(5,3)
arr5[:,0] = values
arr5

array([[ 5.        , -0.67940041,  0.72736878],
       [ 0.        , -1.21385091, -0.47063093],
       [ 1.        , -0.83882669,  0.4351553 ],
       [ 3.        , -0.56745487, -0.37264155],
       [ 2.        ,  1.75510839,  1.20980999]])

In [110]:
arr5[arr5[0].argsort():,1]

SyntaxError: invalid syntax (<ipython-input-110-5efc43ecedbf>, line 1)

In [111]:
arr6 = np.array(['bob','joe','will','bob','joe','joe',
                'will'])

arr6

array(['bob', 'joe', 'will', 'bob', 'joe', 'joe', 'will'], dtype='<U4')

In [112]:
np.unique(arr6)

array(['bob', 'joe', 'will'], dtype='<U4')

In [113]:
arr7 = [2,4,2,6,2,2,7,5,4,1,4,8,6,7]
arr7

[2, 4, 2, 6, 2, 2, 7, 5, 4, 1, 4, 8, 6, 7]

In [114]:
np.unique(arr7)

array([1, 2, 4, 5, 6, 7, 8])

In [115]:
arr8 = np.array([1,2,3,4])
arr9 = np.array([3,4,5,6])
np.union1d(arr8,arr9)

array([1, 2, 3, 4, 5, 6])

In [118]:
np.intersect1d(arr8,arr9)

array([3, 4])

In [119]:
np.setdiff1d(arr8,arr9)

array([1, 2])

In [120]:
arr10 = np.arange(10)
arr10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [122]:
np.random.shuffle(arr10)
arr10

array([7, 8, 0, 2, 3, 5, 1, 6, 9, 4])

In [123]:
arr11 = np.arange(10)
arr11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.random.permutation(arr11)

array([3, 4, 9, 1, 5, 7, 6, 0, 8, 2])

In [125]:
arr11

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [127]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [128]:
np.concatenate([arr1,arr2],0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [129]:
np.concatenate([arr1,arr2],1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [130]:
np.vstack([arr1,arr2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [131]:
np.hstack([arr1,arr2])

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [132]:
arr3 = np.arange(6)
arr4 = np.arange(6).reshape(3,2)
arr5 = np.random.randn(3,2)
arr3

array([0, 1, 2, 3, 4, 5])

In [133]:
arr4

array([[0, 1],
       [2, 3],
       [4, 5]])

In [134]:
arr5

array([[ 1.27002473, -1.37273076],
       [-2.00076104,  1.48407056],
       [ 1.04890629, -1.73763473]])

In [135]:
np.r_[arr4,arr5]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [ 1.27002473, -1.37273076],
       [-2.00076104,  1.48407056],
       [ 1.04890629, -1.73763473]])

In [136]:
np.c_[arr4,arr5]

array([[ 0.        ,  1.        ,  1.27002473, -1.37273076],
       [ 2.        ,  3.        , -2.00076104,  1.48407056],
       [ 4.        ,  5.        ,  1.04890629, -1.73763473]])

In [137]:
np.c_[np.r_[arr4,arr5],arr3]

array([[ 0.        ,  1.        ,  0.        ],
       [ 2.        ,  3.        ,  1.        ],
       [ 4.        ,  5.        ,  2.        ],
       [ 1.27002473, -1.37273076,  3.        ],
       [-2.00076104,  1.48407056,  4.        ],
       [ 1.04890629, -1.73763473,  5.        ]])